server:
  port: 8085
logging:
  config: classpath:log4j2.yml
spring:
  application:
    name: gk5-test-mybatisx
  velocity:
    charset: UTF-8
    properties:
      input:
        encoding: UTF-8
      output:
        encoding: UTF-8
    resourceLoaderPath: classpath:/web/views/
    suffix: .html

cache:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 50
    poolMaxTotal: 500
    poolMaxWaitMillis: -1
    poolMaxIdle: 150
    poolMinIdle: 100
    poolTestOnBorrow: true

datasource:
  mappersPath: wang.bannong.gk5.test.mybatisx.mapper
  primary: master
  dbs:
    - key: master
      host: 127.0.0.1
      port: 3306
      db: gk5
      username: root
      password: '@iam3307'
      minIdle: 10
      maxIdle: 10
      connectionTimeout: 30000
    - key: slave1
      host: 127.0.0.1
      port: 3306
      db: gk5
      username: root
      password: '@iam3307'
      minIdle: 10
      maxIdle: 10
      connectionTimeout: 30000
    - key: slave2
      host: 127.0.0.1
      port: 3306
      db: gk5
      username: root
      password: '@iam3307'
      minIdle: 10
      maxIdle: 10
      connectionTimeout: 30000
